name: Android CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 17
          cache: gradle

      - name: Grant execute permission for gradlew and Build Gradle
        run: chmod +x gradlew && ./gradlew build

      - name: Run Tests
        run: ./gradlew test

  deploy:
    runs-on: windows-latest
    permissions:
      contents: read
      packages: write
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 17
          cache: gradle

      - name: Add RubyGems as source
        run: gem sources --add https://rubygems.org/

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.3' # Use a version supported by your project

      - name: Unset deployment mode
        run: bundle config unset deployment

      - name: Install Bundler
        run: gem install bundler

      - name: Install json gem with --platform=ruby
        run: gem install json -v '2.6.3' --platform=ruby

#bundle install downloads all libs from Gemfile
      - name: Install Bundle
        run: bundle install #--deployment

      - name: Deploy to Firebase - App Distribution
        run: |
          bundle exec fastlane add_plugin firebase_app_distribution
          bundle exec fastlane install_plugins
          bundle exec fastlane deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          ANDROID_VERSION_CODE: ${{github.run_id}}
